import { supabase } from '../supabase/client';
import { toAppError } from '../errors';
import type { TableName } from '../../types/db';

/**
 * Full-account backup and restore.
 *
 * The export is a plain JSON object of table name -> rows, so it stays
 * readable and can be re-imported into a fresh Supabase project.
 */

export const BACKUP_TABLES: TableName[] = [
  'households',
  'profiles',
  'household_settings',
  'units',
  'seasons',
  'farms',
  'crops',
  'farm_crop_allocations',
  'vendors',
  'buyers',
  'expenses',
  'expense_allocations',
  'activities',
  'irrigation_records',
  'spray_records',
  'fertilizer_records',
  'seed_records',
  'harvests',
  'sales',
];

// Rows generated by database triggers must not be re-imported, or the
// mirrored expense would be created twice.
const IMPORT_SKIP: ReadonlySet<TableName> = new Set(['households', 'profiles', 'audit_logs']);

// Generated columns cannot be written back.
const GENERATED_COLUMNS: Partial<Record<TableName, string[]>> = {
  spray_records: ['total_cost'],
  fertilizer_records: ['total_cost'],
  seed_records: ['total_cost'],
  harvests: ['net_quantity', 'total_cost'],
  sales: ['gross_amount', 'net_amount'],
};

export interface BackupFile {
  app: 'farm-hisab';
  version: 1;
  exportedAt: string;
  tables: Partial<Record<TableName, Array<Record<string, unknown>>>>;
}

export async function exportBackup(): Promise<BackupFile> {
  const tables: BackupFile['tables'] = {};
  for (const table of BACKUP_TABLES) {
    const { data, error } = await supabase.from(table).select('*');
    if (error) throw toAppError(error);
    tables[table] = (data ?? []) as Array<Record<string, unknown>>;
  }
  return { app: 'farm-hisab', version: 1, exportedAt: new Date().toISOString(), tables };
}

export function isBackupFile(value: unknown): value is BackupFile {
  return (
    typeof value === 'object' &&
    value !== null &&
    (value as BackupFile).app === 'farm-hisab' &&
    typeof (value as BackupFile).tables === 'object'
  );
}

/**
 * Restores a backup into the signed-in household.
 * Existing rows are left untouched (`ignoreDuplicates`), so an import can be
 * repeated safely and never deletes anything.
 */
export async function importBackup(backup: BackupFile, householdId: string): Promise<number> {
  let imported = 0;
  for (const table of BACKUP_TABLES) {
    if (IMPORT_SKIP.has(table)) continue;
    const rows = backup.tables[table];
    if (!rows || rows.length === 0) continue;

    const generated = GENERATED_COLUMNS[table] ?? [];
    const payload = rows.map((row) => {
      const copy: Record<string, unknown> = { ...row, household_id: householdId };
      for (const column of generated) delete copy[column];
      return copy;
    });

    // Chunked so a large backup does not exceed request limits.
    for (let index = 0; index < payload.length; index += 200) {
      const chunk = payload.slice(index, index + 200);
      const { error } = await supabase.from(table).upsert(chunk, { onConflict: 'id', ignoreDuplicates: true });
      if (error) throw toAppError(error);
      imported += chunk.length;
    }
  }
  return imported;
}
